import pmdocs
from conftest import INDEX
from helpers import has, run_cli, write
from test_model import PLAN, SPEC, plan_text, spec_text


def cfg(repo):
    return pmdocs.load_config(repo)


def read(repo, rel):
    return (repo / rel).read_text(encoding="utf-8")


def nav_of(page_html):
    return page_html.split('<nav class="side">', 1)[1].split("</nav>", 1)[0]


def test_build_creates_site_and_roadmap(repo):
    changed = pmdocs.build(cfg(repo))
    assert {"docs/roadmap.md", "docs/site/index.html", "docs/site/roadmap.html"} <= set(changed)
    page = read(repo, "docs/site/index.html")
    assert "<title>Demo — demo</title>" in page
    assert page.count("<h1>") == 1 and "<h1>Demo</h1>" in page
    assert "GENERATED by scripts/pmdocs.py from docs/index.md" in page
    assert '<p class="summary">Demo project.</p>' in page


def test_build_is_idempotent(repo):
    pmdocs.build(cfg(repo))
    assert pmdocs.build(cfg(repo)) == []
    assert pmdocs.build(cfg(repo), check=True) == []


def test_check_detects_stale(repo):
    pmdocs.build(cfg(repo))
    write(repo, "docs/index.md", INDEX.replace("Hello.", "Changed."))
    assert pmdocs.build(cfg(repo), check=True) == ["docs/site/index.html"]
    assert "Hello." in read(repo, "docs/site/index.html")  # --check wrote nothing
    r = run_cli(repo, "build", "--check")
    assert r.returncode == 1 and "stale: docs/site/index.html" in r.stdout


def test_build_cli(repo):
    r = run_cli(repo, "build")
    assert r.returncode == 0 and "file(s) updated" in r.stdout
    r = run_cli(repo, "build")
    assert "site up to date" in r.stdout


def test_links_rewritten(repo):
    write(repo, "src/a.py", "x = 1\n")
    write(repo, "docs/architecture.md", "---\ntitle: Arch\n---\n\n# Arch\n\n## Data flow\n")
    write(repo, "docs/index.md", "---\ntitle: Demo\n---\n\n[a](architecture.md#data-flow) "
          "[c](../src/a.py) ![d](img/d.png) [w](https://example.com/x.md)\n")
    (repo / "docs/img").mkdir()
    (repo / "docs/img/d.png").write_bytes(b"PNG")
    pmdocs.build(cfg(repo))
    page = read(repo, "docs/site/index.html")
    assert 'href="architecture.html#data-flow"' in page
    assert 'href="../../src/a.py"' in page
    assert 'src="img/d.png"' in page
    assert 'href="https://example.com/x.md"' in page
    assert (repo / "docs/site/img/d.png").read_bytes() == b"PNG"


def test_nested_page_links_and_meta(repo):
    write(repo, SPEC, spec_text("shipped") + "\nSee [backlog](../../backlog.md).\n")
    write(repo, PLAN, plan_text("in-progress"))
    write(repo, "docs/backlog.md", "---\ntitle: Backlog\n---\n\n# Backlog\n")
    pmdocs.build(cfg(repo))
    spec_html = read(repo, "docs/site/superpowers/specs/2026-09-01-x-design.html")
    assert 'href="../../backlog.html"' in spec_html
    assert 'class="badge s-shipped"' in spec_html
    plan_html = read(repo, "docs/site/superpowers/plans/2026-09-02-x.html")
    assert 'spec: <a href="../specs/2026-09-01-x-design.html">X</a>' in plan_html


def test_status_badge_class_only_from_known_statuses(repo):
    write(repo, SPEC, spec_text("weird status"))
    pmdocs.build(cfg(repo))
    spec_html = read(repo, "docs/site/superpowers/specs/2026-09-01-x-design.html")
    assert '<span class="badge s-other">weird status</span>' in spec_html


def test_heading_ids_and_toc(repo):
    write(repo, "docs/architecture.md", "---\ntitle: Arch\n---\n\n# Arch\n\n## One\n\n### Two\n\n## One\n")
    pmdocs.build(cfg(repo))
    page = read(repo, "docs/site/architecture.html")
    for fragment in ('<h2 id="one">', '<h3 id="two">', '<h2 id="one-1">', 'href="#one-1"'):
        assert fragment in page
    # the TOC is collapsible and starts collapsed, so it costs one line until opened
    assert '<details class="toc"><summary>On this page</summary>' in page
    assert "<details class=\"toc\" open" not in page


def outline(page_html):
    """The sidebar as text: page titles (indented two spaces per nesting level),
    '# Heading' for group headings, '---' for a divider."""
    from html.parser import HTMLParser

    class P(HTMLParser):
        def __init__(self):
            super().__init__()
            self.out, self.uls, self.in_h2, self.in_a = [], [], False, False

        def handle_starttag(self, tag, attrs):
            a = dict(attrs)
            if tag == "ul":
                self.uls.append(a.get("class", ""))
                if a.get("class") == "continued":
                    self.out.append("---")
            self.in_h2 = self.in_h2 or tag == "h2"
            self.in_a = self.in_a or (tag == "a" and "site" not in (a.get("class") or ""))

        def handle_endtag(self, tag):
            if tag == "ul":
                self.uls.pop()
            self.in_h2 = self.in_h2 and tag != "h2"
            self.in_a = self.in_a and tag != "a"

        def handle_data(self, data):
            if self.in_h2:
                self.out.append("# " + data)
            elif self.in_a:
                self.out.append("  " * self.uls.count("children") + data)

    p = P()
    p.feed(nav_of(page_html))
    return p.out


def tree_repo(repo):
    for rel, fm in [("docs/backlog.md", "title: Backlog"),
                    ("docs/backlog-archive.md", "title: Backlog archive"),
                    ("docs/product.md", "title: Product"),
                    ("docs/architecture.md", "title: Architecture"),
                    ("docs/decisions.md", "title: Decisions"),
                    ("docs/install.md", "title: Install\nparent: overview"),
                    ("docs/code-layout.md", "title: Code layout\nparent: architecture\norder: 2"),
                    ("docs/palette.md", "title: Palette\nparent: architecture\norder: 1"),
                    ("docs/notes/decision-log.md", "title: Decision log\nparent: decisions"),
                    ("docs/scratch.md", "title: Scratch")]:
        write(repo, rel, f"---\n{fm}\n---\n")
    write(repo, SPEC, spec_text())
    write(repo, PLAN, plan_text())
    write(repo, "README.md", "# Demo repo\n")


def test_sidebar_is_the_fixed_category_tree(repo):
    tree_repo(repo)
    pmdocs.build(cfg(repo))
    assert outline(read(repo, "docs/site/index.html")) == [
        "Demo", "  Install",
        "Roadmap",
        "Backlog",
        "Product",
        "Architecture", "  Palette", "  Code layout",
        "Decisions", "  Decision log",
        "# Specs", "X",
        "# Plans", "X plan",
        "# Repository", "Demo repo",
        "# Other", "Scratch",
        "---", "Backlog archive",
    ]
    assert 'aria-current="page">Demo</a>' in nav_of(read(repo, "docs/site/index.html"))


def test_missing_category_pages_are_simply_absent(repo):
    pmdocs.build(cfg(repo))
    assert outline(read(repo, "docs/site/index.html")) == ["Demo", "Roadmap"]


def test_page_without_parent_warns(repo):
    tree_repo(repo)
    f = pmdocs.validate(pmdocs.load_model(cfg(repo)))
    assert has(f, "WARN", "no parent")
    assert [x.where for x in f if x.level == "WARN"] == ["docs/scratch.md"]


def test_bad_parent_is_error(repo):
    write(repo, "docs/x.md", "---\ntitle: X\nparent: backlog\n---\n")
    f = pmdocs.validate(pmdocs.load_model(cfg(repo)))
    assert has(f, "ERROR", "parent 'backlog' is not one of overview, product, architecture, decisions")


def test_parent_whose_page_is_missing_warns_and_lists_under_other(repo):
    write(repo, "docs/x.md", "---\ntitle: X page\nparent: product\n---\n")
    assert has(pmdocs.validate(pmdocs.load_model(cfg(repo))), "WARN", "docs/product.md does not exist")
    pmdocs.build(cfg(repo))
    assert outline(read(repo, "docs/site/index.html"))[-2:] == ["# Other", "X page"]


def test_site_nav_setting_is_rejected(repo):
    write(repo, "docs/pmdocs.toml", '[site]\ntitle = "demo"\nnav = ["docs/index.md"]\n')
    assert has(pmdocs.validate(pmdocs.load_model(cfg(repo))), "ERROR",
               "[site] nav was removed in pmdocs 0.2.0")


EXTRA_CONFIG = '[site]\ntitle = "demo"\nextra = ["skill/*.md", "skill/references/*.md"]\n'


def with_extra(repo):
    write(repo, "docs/pmdocs.toml", EXTRA_CONFIG)
    write(repo, "skill/SKILL.md", "---\nname: my-skill\ndescription: Use when testing.\n---\n\n# My skill\n\nBody.\n")
    write(repo, "skill/references/guide.md", "# The guide\n\n## Part one\n\nSee [the skill](../SKILL.md).\n")
    write(repo, "docs/index.md", "---\ntitle: Demo\n---\n\n[guide](../skill/references/guide.md#part-one)\n")


def test_extra_files_are_rendered_in_a_reference_group(repo):
    with_extra(repo)
    pmdocs.build(cfg(repo))
    guide = read(repo, "docs/site/extra/skill/references/guide.html")
    assert "<h1>The guide</h1>" in guide                       # title from the first H1
    assert 'href="../SKILL.html"' in guide                      # extra-to-extra link
    skill = read(repo, "docs/site/extra/skill/SKILL.html")
    assert "<h1>my-skill</h1>" in skill                         # title from frontmatter name
    assert '<p class="summary">Use when testing.</p>' in skill  # description as summary
    index = read(repo, "docs/site/index.html")
    assert 'href="extra/skill/references/guide.html#part-one"' in index
    o = outline(index)
    assert o.index("# Reference") < o.index("The guide")


def test_extra_files_need_no_frontmatter_but_links_are_checked(repo):
    with_extra(repo)
    write(repo, "skill/references/broken.md", "# Broken\n\n[nope](missing.md)\n")
    model = pmdocs.load_model(cfg(repo))
    assert pmdocs.validate(model) == []
    assert [f.msg for f in pmdocs.check_links(model)] == ["broken link missing.md"]


GROUP_CONFIG = ('[site]\ntitle = "demo"\n\n'
                '[[site.extra]]\ngroup = "The skill"\n'
                'about = "The skill\'s own files, rendered for reading."\n'
                'paths = ["skill/*.md", "skill/references/*.md"]\n')


def test_extra_page_shows_its_source(repo):
    with_extra(repo)
    pmdocs.build(cfg(repo))
    guide = read(repo, "docs/site/extra/skill/references/guide.html")
    assert ('Source: <a href="../../../../../skill/references/guide.md">'
            "<code>skill/references/guide.md</code></a>") in guide
    assert "outside <code>docs/</code>" in guide


def test_named_extra_group_with_about(repo):
    with_extra(repo)
    write(repo, "docs/pmdocs.toml", GROUP_CONFIG)
    model = pmdocs.load_model(cfg(repo))
    assert pmdocs.validate(model) == []
    pmdocs.build(cfg(repo))
    o = outline(read(repo, "docs/site/index.html"))
    assert "# The skill" in o and "# Reference" not in o
    skill = read(repo, "docs/site/extra/skill/SKILL.html")
    assert '<p class="about">The skill&#x27;s own files, rendered for reading.</p>' in skill


def test_extra_group_pages_follow_the_listed_path_order(repo):
    with_extra(repo)
    write(repo, "skill/references/another.md", "# Another\n")
    write(repo, "docs/pmdocs.toml", GROUP_CONFIG.replace(
        'paths = ["skill/*.md", "skill/references/*.md"]',
        'paths = ["skill/references/guide.md", "skill/*.md", "skill/references/*.md"]'))
    pmdocs.build(cfg(repo))
    o = outline(read(repo, "docs/site/index.html"))
    start = o.index("# The skill") + 1
    assert o[start:start + 3] == ["The guide", "my-skill", "Another"]


def test_root_readme_is_rendered_by_default(repo):
    write(repo, "README.md", "# Demo repo\n\nSee [the docs](docs/index.md).\n")
    pmdocs.build(cfg(repo))
    readme = read(repo, "docs/site/extra/README.html")
    assert "<h1>Demo repo</h1>" in readme and 'href="../index.html"' in readme
    o = outline(read(repo, "docs/site/index.html"))
    assert o[o.index("# Repository") + 1] == "Demo repo"


def test_readme_can_be_turned_off(repo):
    write(repo, "README.md", "# Demo repo\n")
    write(repo, "docs/pmdocs.toml", '[site]\ntitle = "demo"\nreadme = false\n')
    pmdocs.build(cfg(repo))
    assert not (repo / "docs/site/extra/README.html").exists()


def test_readme_listed_explicitly_is_not_duplicated(repo):
    write(repo, "README.md", "# Demo repo\n")
    write(repo, "docs/pmdocs.toml",
          '[site]\ntitle = "demo"\n\n[[site.extra]]\ngroup = "Front page"\npaths = ["README.md"]\n')
    pmdocs.build(cfg(repo))
    o = outline(read(repo, "docs/site/index.html"))
    assert "# Front page" in o and "# Repository" not in o and o.count("Demo repo") == 1


def test_no_readme_no_group(repo):
    pmdocs.build(cfg(repo))
    assert "Repository" not in read(repo, "docs/site/index.html")


def test_orphans_removed(repo):
    write(repo, "docs/old.md", "---\ntitle: Old\n---\n")
    pmdocs.build(cfg(repo))
    assert (repo / "docs/site/old.html").is_file()
    (repo / "docs/old.md").unlink()
    assert "docs/site/old.html" in pmdocs.build(cfg(repo))
    assert not (repo / "docs/site/old.html").exists()


def test_build_keeps_files_it_did_not_generate(repo):
    pmdocs.build(cfg(repo))
    write(repo, "docs/site/scratch.txt", "mine\n")
    assert "docs/site/scratch.txt" not in pmdocs.build(cfg(repo))
    assert (repo / "docs/site/scratch.txt").read_text(encoding="utf-8") == "mine\n"


def test_excluded_pages_not_rendered(repo):
    write(repo, "docs/pmdocs.toml", '[paths]\nexclude = ["docs/course/**"]\n')
    write(repo, "docs/course/l1.md", "# No frontmatter\n")
    pmdocs.build(cfg(repo))
    assert not (repo / "docs/site/course").exists()


def test_crlf_site_not_stale(repo):
    pmdocs.build(cfg(repo))
    p = repo / "docs/site/index.html"
    p.write_bytes(p.read_bytes().replace(b"\n", b"\r\n"))
    assert pmdocs.build(cfg(repo), check=True) == []


def test_raw_html_passes_through(repo):
    write(repo, "docs/index.md", "---\ntitle: Demo\n---\n\n<svg viewBox=\"0 0 1 1\"></svg>\n")
    pmdocs.build(cfg(repo))
    assert '<svg viewBox="0 0 1 1"></svg>' in read(repo, "docs/site/index.html")
