import pmdocs
from conftest import INDEX
from helpers import has, run_cli, write
from test_model import PLAN, SPEC, plan_text, spec_text


def cfg(repo):
    return pmdocs.load_config(repo)


def read(repo, rel):
    return (repo / rel).read_text(encoding="utf-8")


def nav_of(page_html):
    return page_html.split('<nav class="side">', 1)[1].split("</nav>", 1)[0]


def test_build_creates_site_and_roadmap(repo):
    changed = pmdocs.build(cfg(repo))
    assert {"docs/roadmap.md", "docs/site/index.html", "docs/site/roadmap.html"} <= set(changed)
    page = read(repo, "docs/site/index.html")
    assert "<title>Demo — demo</title>" in page
    assert page.count("<h1>") == 1 and "<h1>Demo</h1>" in page
    assert "GENERATED by scripts/pmdocs.py from docs/index.md" in page
    assert '<p class="summary">Demo project.</p>' in page


def test_build_is_idempotent(repo):
    pmdocs.build(cfg(repo))
    assert pmdocs.build(cfg(repo)) == []
    assert pmdocs.build(cfg(repo), check=True) == []


def test_check_detects_stale(repo):
    pmdocs.build(cfg(repo))
    write(repo, "docs/index.md", INDEX.replace("Hello.", "Changed."))
    assert pmdocs.build(cfg(repo), check=True) == ["docs/site/index.html"]
    assert "Hello." in read(repo, "docs/site/index.html")  # --check wrote nothing
    r = run_cli(repo, "build", "--check")
    assert r.returncode == 1 and "stale: docs/site/index.html" in r.stdout


def test_build_cli(repo):
    r = run_cli(repo, "build")
    assert r.returncode == 0 and "file(s) updated" in r.stdout
    r = run_cli(repo, "build")
    assert "site up to date" in r.stdout


def test_links_rewritten(repo):
    write(repo, "src/a.py", "x = 1\n")
    write(repo, "docs/architecture.md", "---\ntitle: Arch\n---\n\n# Arch\n\n## Data flow\n")
    write(repo, "docs/index.md", "---\ntitle: Demo\n---\n\n[a](architecture.md#data-flow) "
          "[c](../src/a.py) ![d](img/d.png) [w](https://example.com/x.md)\n")
    (repo / "docs/img").mkdir()
    (repo / "docs/img/d.png").write_bytes(b"PNG")
    pmdocs.build(cfg(repo))
    page = read(repo, "docs/site/index.html")
    assert 'href="architecture.html#data-flow"' in page
    assert 'href="../../src/a.py"' in page
    assert 'src="img/d.png"' in page
    assert 'href="https://example.com/x.md"' in page
    assert (repo / "docs/site/img/d.png").read_bytes() == b"PNG"


def test_nested_page_links_and_meta(repo):
    write(repo, SPEC, spec_text("shipped") + "\nSee [backlog](../../backlog.md).\n")
    write(repo, PLAN, plan_text("in-progress"))
    write(repo, "docs/backlog.md", "---\ntitle: Backlog\n---\n\n# Backlog\n")
    pmdocs.build(cfg(repo))
    spec_html = read(repo, "docs/site/superpowers/specs/2026-09-01-x-design.html")
    assert 'href="../../backlog.html"' in spec_html
    assert 'class="badge s-shipped"' in spec_html
    plan_html = read(repo, "docs/site/superpowers/plans/2026-09-02-x.html")
    assert 'spec: <a href="../specs/2026-09-01-x-design.html">X</a>' in plan_html


def test_status_badge_class_only_from_known_statuses(repo):
    write(repo, SPEC, spec_text("weird status"))
    pmdocs.build(cfg(repo))
    spec_html = read(repo, "docs/site/superpowers/specs/2026-09-01-x-design.html")
    assert '<span class="badge s-other">weird status</span>' in spec_html


def test_heading_ids_and_toc(repo):
    write(repo, "docs/architecture.md", "---\ntitle: Arch\n---\n\n# Arch\n\n## One\n\n### Two\n\n## One\n")
    pmdocs.build(cfg(repo))
    page = read(repo, "docs/site/architecture.html")
    for fragment in ('<h2 id="one">', '<h3 id="two">', '<h2 id="one-1">', 'href="#one-1"'):
        assert fragment in page
    # the TOC is collapsible and starts collapsed, so it costs one line until opened
    assert '<details class="toc"><summary>On this page</summary>' in page
    assert "<details class=\"toc\" open" not in page


def test_nav_order_and_groups(repo):
    write(repo, "docs/architecture.md", "---\ntitle: Architecture\norder: 20\n---\n")
    write(repo, "docs/product.md", "---\ntitle: Product\norder: 10\n---\n")
    write(repo, SPEC, spec_text())
    write(repo, PLAN, plan_text())
    pmdocs.build(cfg(repo))
    nav = nav_of(read(repo, "docs/site/index.html"))
    assert nav.index(">Demo</a>") < nav.index(">Roadmap</a>") < nav.index(">Product</a>") \
        < nav.index(">Architecture</a>") < nav.index("<h2>Specs</h2>") < nav.index("<h2>Plans</h2>")
    assert 'aria-current="page">Demo</a>' in nav


NAV_CONFIG = ('[site]\ntitle = "demo"\nnav = ["docs/index.md", "docs/roadmap.md", "docs/backlog.md", '
              '"docs/product.md", "Specs", "docs/backlog-archive.md"]\n')


def nav_entries(page_html):
    import re
    return re.findall(r"<h2>([^<]+)</h2>|>([^<>]+)</a></li>", nav_of(page_html))


def test_nav_list_orders_pages_and_groups(repo):
    write(repo, "docs/pmdocs.toml", NAV_CONFIG)
    for name, title in [("product", "Product"), ("architecture", "Architecture"),
                        ("backlog", "Backlog"), ("backlog-archive", "Backlog archive")]:
        write(repo, f"docs/{name}.md", f"---\ntitle: {title}\n---\n")
    write(repo, SPEC, spec_text())
    write(repo, PLAN, plan_text())
    pmdocs.build(cfg(repo))
    flat = [h or p for h, p in nav_entries(read(repo, "docs/site/index.html"))]
    assert flat == ["Docs", "Demo", "Roadmap", "Backlog", "Product",
                    "Specs", "X",
                    "Backlog archive",            # a listed page after a group: its own run, no heading
                    "More", "Architecture",       # unlisted top-level pages
                    "Plans", "X plan"]            # unlisted groups keep their default order


def test_nav_run_after_a_group_has_no_heading(repo):
    write(repo, "docs/pmdocs.toml", NAV_CONFIG)
    write(repo, "docs/backlog-archive.md", "---\ntitle: Backlog archive\n---\n")
    write(repo, SPEC, spec_text())
    pmdocs.build(cfg(repo))
    nav = nav_of(read(repo, "docs/site/index.html"))
    between = nav.split(">X</a>", 1)[1].split(">Backlog archive</a>", 1)[0]
    assert "<h2>" not in between
    # ...but it is visibly a new section, not a continuation of the group above it
    assert '<ul class="continued">' in between


def test_nav_unknown_entry_is_error(repo):
    write(repo, "docs/pmdocs.toml", '[site]\nnav = ["docs/nope.md", "Spex"]\n')
    f = pmdocs.validate(pmdocs.load_model(cfg(repo)))
    assert has(f, "ERROR", "nav entry 'docs/nope.md' is not a page or a nav group")
    assert has(f, "ERROR", "nav entry 'Spex' is not a page or a nav group")


EXTRA_CONFIG = '[site]\ntitle = "demo"\nextra = ["skill/*.md", "skill/references/*.md"]\n'


def with_extra(repo):
    write(repo, "docs/pmdocs.toml", EXTRA_CONFIG)
    write(repo, "skill/SKILL.md", "---\nname: my-skill\ndescription: Use when testing.\n---\n\n# My skill\n\nBody.\n")
    write(repo, "skill/references/guide.md", "# The guide\n\n## Part one\n\nSee [the skill](../SKILL.md).\n")
    write(repo, "docs/index.md", "---\ntitle: Demo\n---\n\n[guide](../skill/references/guide.md#part-one)\n")


def test_extra_files_are_rendered_in_a_reference_group(repo):
    with_extra(repo)
    pmdocs.build(cfg(repo))
    guide = read(repo, "docs/site/extra/skill/references/guide.html")
    assert "<h1>The guide</h1>" in guide                       # title from the first H1
    assert 'href="../SKILL.html"' in guide                      # extra-to-extra link
    skill = read(repo, "docs/site/extra/skill/SKILL.html")
    assert "<h1>my-skill</h1>" in skill                         # title from frontmatter name
    assert '<p class="summary">Use when testing.</p>' in skill  # description as summary
    index = read(repo, "docs/site/index.html")
    assert 'href="extra/skill/references/guide.html#part-one"' in index
    flat = [h or p for h, p in nav_entries(index)]
    assert flat.index("Reference") < flat.index("The guide")


def test_extra_files_need_no_frontmatter_but_links_are_checked(repo):
    with_extra(repo)
    write(repo, "skill/references/broken.md", "# Broken\n\n[nope](missing.md)\n")
    model = pmdocs.load_model(cfg(repo))
    assert pmdocs.validate(model) == []
    assert [f.msg for f in pmdocs.check_links(model)] == ["broken link missing.md"]


GROUP_CONFIG = ('[site]\ntitle = "demo"\nnav = ["docs/index.md", "The skill"]\n\n'
                '[[site.extra]]\ngroup = "The skill"\n'
                'about = "The skill\'s own files, rendered for reading."\n'
                'paths = ["skill/*.md", "skill/references/*.md"]\n')


def test_extra_page_shows_its_source(repo):
    with_extra(repo)
    pmdocs.build(cfg(repo))
    guide = read(repo, "docs/site/extra/skill/references/guide.html")
    assert ('Source: <a href="../../../../../skill/references/guide.md">'
            "<code>skill/references/guide.md</code></a>") in guide
    assert "outside <code>docs/</code>" in guide


def test_named_extra_group_with_about(repo):
    with_extra(repo)
    write(repo, "docs/pmdocs.toml", GROUP_CONFIG)
    model = pmdocs.load_model(cfg(repo))
    assert pmdocs.validate(model) == []  # "The skill" is a valid nav group
    pmdocs.build(cfg(repo))
    index = read(repo, "docs/site/index.html")
    flat = [h or p for h, p in nav_entries(index)]
    assert flat[:3] == ["Docs", "Demo", "The skill"] and "Reference" not in flat
    skill = read(repo, "docs/site/extra/skill/SKILL.html")
    assert '<p class="about">The skill&#x27;s own files, rendered for reading.</p>' in skill


def test_extra_group_pages_follow_the_listed_path_order(repo):
    with_extra(repo)
    write(repo, "skill/references/another.md", "# Another\n")
    write(repo, "docs/pmdocs.toml", GROUP_CONFIG.replace(
        'paths = ["skill/*.md", "skill/references/*.md"]',
        'paths = ["skill/references/guide.md", "skill/*.md", "skill/references/*.md"]'))
    pmdocs.build(cfg(repo))
    flat = [h or p for h, p in nav_entries(read(repo, "docs/site/index.html"))]
    start = flat.index("The skill") + 1
    assert flat[start:start + 3] == ["The guide", "my-skill", "Another"]


def test_nav_can_place_the_reference_group(repo):
    with_extra(repo)
    write(repo, "docs/pmdocs.toml", EXTRA_CONFIG.replace("extra =", 'nav = ["Reference", "docs/index.md"]\nextra ='))
    pmdocs.build(cfg(repo))
    flat = [h or p for h, p in nav_entries(read(repo, "docs/site/index.html"))]
    assert flat[:2] == ["Reference", "my-skill"]
    assert pmdocs.validate(pmdocs.load_model(cfg(repo))) == []


def test_orphans_removed(repo):
    write(repo, "docs/old.md", "---\ntitle: Old\n---\n")
    pmdocs.build(cfg(repo))
    assert (repo / "docs/site/old.html").is_file()
    (repo / "docs/old.md").unlink()
    assert "docs/site/old.html" in pmdocs.build(cfg(repo))
    assert not (repo / "docs/site/old.html").exists()


def test_build_keeps_files_it_did_not_generate(repo):
    pmdocs.build(cfg(repo))
    write(repo, "docs/site/scratch.txt", "mine\n")
    assert "docs/site/scratch.txt" not in pmdocs.build(cfg(repo))
    assert (repo / "docs/site/scratch.txt").read_text(encoding="utf-8") == "mine\n"


def test_excluded_pages_not_rendered(repo):
    write(repo, "docs/pmdocs.toml", '[paths]\nexclude = ["docs/course/**"]\n')
    write(repo, "docs/course/l1.md", "# No frontmatter\n")
    pmdocs.build(cfg(repo))
    assert not (repo / "docs/site/course").exists()


def test_crlf_site_not_stale(repo):
    pmdocs.build(cfg(repo))
    p = repo / "docs/site/index.html"
    p.write_bytes(p.read_bytes().replace(b"\n", b"\r\n"))
    assert pmdocs.build(cfg(repo), check=True) == []


def test_raw_html_passes_through(repo):
    write(repo, "docs/index.md", "---\ntitle: Demo\n---\n\n<svg viewBox=\"0 0 1 1\"></svg>\n")
    pmdocs.build(cfg(repo))
    assert '<svg viewBox="0 0 1 1"></svg>' in read(repo, "docs/site/index.html")
